# Config file for automatic testing at travis-ci.org
language: python
jobs:
  include:
    - name: Python 3.6 on Linux (dist:xenial)"
      os: linux
      dist: xenial
      language: python
      python: 3.6
      env: python_version=3.6

    - name: "Python 3.7 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.7
      env: python_version=3.7

    - name: "Python 3.8 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.8
      env: python_version=3.8

    - name: "Python 3.9 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.9
      env: python_version=3.9

    - name: "Python 3.10 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.10
      env: python_version=3.10

    - name: "Python 3.11 on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.11
      env: python_version=3.11

    - name: "Python 3.12-dev on Linux (dist:jammy)"
      os: linux
      dist: jammy
      language: python
      python: 3.12-dev
      env: python_version=3.12-dev

  allow_failures:
    - python: 3.12-dev

cache:
  directories:
    - eggs

install:
  - pip install -U pip
  - pip install flit
  - pip install codecov
  - flit install --extras test
  - sleep 1

script:
  - make clean
  - mypy fhirspec.py
  - isort -c fhirspec.py
  - black --check --verbose fhirspec.py
  - pytest -s --cov=tests -s --tb=native -v --cov-report term-missing --cov-append tests

after_success:
  - codecov

